### PR TITLE
WIP:  US flag emoji (aka "us")

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@wsargent  

It would be nice to be able to reference the US Flag with the shortcode "us"

In the current implementation, Emoji.scala assumes that an emoji is represented by a single codepoint.

Country Flag emojis are defined by two codepoints. For the US flag ("us"), the first codepoint is "regional indicator u" and the second codepoint is "regional indicator s"

I am not sure how to support ShortCode "us" without changing Emoji.scala

**Comment by wsargent** [comment]
@sullis we're going to have to upgrade emoji to take an array of codepoints.  It's time for 2.0 :-D

**Comment by sullis** [comment]
similar approach:  [emoji-java] uses a String field ("unicode") in Emoji.java

https://github.com/vdurmont/emoji-java/blob/master/src/main/java/com/vdurmont/emoji/Emoji.java

**Comment by SethTisue** [comment]
looks like work here his stalled. closing as stale, can be reopened if work resumes

**Pull request closed without merging**
