### PR TITLE
Add Emojilator for embedded short names

### PR DESCRIPTION
**Pull request by som-snytt**
As requested on gitter.

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM, but would need accompanying doc in README.md. @wsargent, what do you think?

**Comment by wsargent** [comment]
"colonoscope" really?

**Comment by som-snytt** [comment]
I'll update it to "Colonus", as in Oedipus blind and near death.

I'll also revise the test to I :heart: :older_woman:, :eyes: :hurtrealbad: like :face_with_head_bandage:

**Comment by SethTisue** [comment]
keeping it family friendly aids enterprise uptake

**Comment by SethTisue** [comment]
keeping it family friendly aids enterprise uptake

and who is the poster child for "family friendly" if not Oedipus?

**Comment by som-snytt** [comment]
Cleaned it up.

**Comment by SethTisue** [comment]
LGTM, but still needs doc in README.md

**Comment by SethTisue** [comment]
🏁

**Comment by som-snytt** [comment]
I don't mind going the distance. Thanks again for your attention to detail and keeping me from doing something embarrassing. Any remaining embarrassments are, of course, my own.

I'll create an issue to support `e"\:"` instead of double colon; I was too lazy, and `StringContext` doesn't make it trivial. I considered catching `InvalidEscapeException` and fixing escaped colon that way. That would be embarrassing, but maybe less than `e"::"`.

The other desirable feature would be to handle emoticons, `e":)"`. That was too much for a weekday and might require a SIP or something.

**Comment by SethTisue** [comment]
> That was too much for a weekday and might require a SIP or something

alternative plan: ⛱🍹

**Pull request merged**
