### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by SethTisue** [comment]
@Philippus the only ScalaTest version available for 2.13.0-M3 is 3.0.5-M1, hence the Travis-CI failure

**Comment by Philippus** [comment]
ok, I went back to 2.13.0-M2

**Comment by SethTisue** [comment]
works for me! lightbend-emoji is in the 2.13 community build, so if anything breaks on the later 2.13 milestones I expect to find out that way well in advance of 2.13 final.

**Comment by SethTisue** [comment]
thank you! 🏆 🍰 🎆 🐱 ✨

**Pull request merged**
