### PR TITLE
Scala version bumps (2.13.4, 3.0.0-M2)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
gah, Travis-CI isn't running... investigating

**Comment by SethTisue** [comment]
hmm, it seems we weren't enabled on travis-ci.com, so I enabled the repo, but now I see at https://travis-ci.com/github/lightbend/lightbend-emoji we had done that before, so maybe somebody at Lightbend disabled it? because the orig is over its OSS allotment? sigh

**Comment by SethTisue** [comment]
oh well, I ran `+test` and `+mimaReportBinaryIssues` and `+package` locally

**Comment by SethTisue** [comment]
@Philippus I don't suppose you've been looking for an opportunity to gain light familiarity with GitHub Actions? I've been dodging that so far... I mean, I'm sure I'll need to learn it eventually

**Comment by Philippus** [comment]
I've only set up the basic stuff, but not for isntalling adoptopenjdk (which we use here) or publishing (which we don't).
I did find https://github.com/olafurpg/setup-scala which looks like it does the first.

**Pull request merged**
