### PR TITLE
Add similar works

### PR DESCRIPTION
**Pull request by wsargent**

### CODE REVIEW

**Comment by som-snytt** [comment]
Similar Works

These libraries have not been evaluated, and they may work or not, and they may or may not work similarly.

**Comment by SethTisue** [comment]
every PhD thesis needs a "related works" chapter

**Comment by wsargent** [comment]
> These libraries have not been evaluated, and they may work or not, **and they may or may not work similarly.**

Wouldn't they then be dissimilar works?

**Comment by wsargent** [comment]
If you could include both the projects are similar and the projects that are not similar, that would be a big help, thanks.

**Pull request merged**
