### PR TITLE
add Scala 2.13.0-M2 to crossbuild

### PR DESCRIPTION
**Pull request by SethTisue**
and make Travis test all of the supported Scala versions

### CODE REVIEW

**Comment by SethTisue** [comment]
it's perhaps a bit nicer to list the Scala versions in `.travis.yml` since then you get a separate Travis log for each version, but this way is easier to set up and doesn't require maintaining two lists of Scala versions

**Comment by SethTisue** [comment]
Travis likes it, but he's a pushover compared to @wsargent

**Comment by wsargent** [comment]
Should compare against java9 as well (although maybe that should be a different PR).  
See https://github.com/playframework/play-scala-secure-session-example/pull/56 for example:

```
jdk:
  - oraclejdk8		  
  - oraclejdk9

matrix:
   exclude:
     - scala: 2.11.12
        jdk: oraclejdk9
```

**Comment by SethTisue** [comment]
sbt 1.0.x's Java 9 support isn't super solid yet, so I suggest we wait and add Java 9 support here once sbt 1.1 has been out a little while

**Pull request merged**
