### PR TITLE
Use dotty style

### PR DESCRIPTION
**Pull request by som-snytt**
Update 2.12.16 and follow up https://github.com/lightbend/lightbend-emoji/pull/172

Might entail lightbend-emoji 1.3.

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt mind giving this a quick rebase?

@Philippus any thoughts on the changes?

**Comment by som-snytt** [comment]
I did my first ever `git rebase --skip` because even though I was there first, who can compete with a bot? I am always quick to blame the bots, that scourge of online culture.

**Review by Philippus — COMMENTED** [review]
Maybe this requires the `project.layout`-setting (https://scalameta.org/scalafmt/docs/configuration.html#projectlayout) to keep scalafmt happy?

**Comment by som-snytt** [comment]
I've never used scalafmt; I'd be willing to learn a bit, as this is an educational PR, but the docs look like you try to dip a toe in the water and the rip tide sucks you away.

It's not configured for sbt, and I see
> NB: keep in mind that versions of scalafmt-core and sbt-scalafmt are released independently, their versions do not align. The version of scalafmt-core is defined in the .scalafmt.conf configuration file and downloaded dynamically

The doc at the link for `project.layout` says
> Allows specifying a project structure naming convention which can be used to select an appropriate dialect for cross-building if one is explicitly selected via [fileOverride](https://scalameta.org/scalafmt/docs/configuration.html#fileoverride).

Perhaps it meant to say the opposite: "if one is *not* explicitly selected".

I can add `project.layout=StandardConvention` to `.scalafmt.conf` but I am not likely to exercise it within a reasonable time frame.

**Comment by SethTisue** [comment]
thanks Som!

**Pull request merged**
